# fish completion for tgrep
# Generated from `/Users/ama/.local/share/mise/installs/github-microsoft-tgrep/latest/tgrep -h` (tgrep 1.0.3)
# Trigram-indexed grep — fast regex search for large codebases

complete -e -c tgrep

# Subcommands
complete -c tgrep -n __fish_use_subcommand -f -a index -d 'Build or rebuild the trigram index'
complete -c tgrep -n __fish_use_subcommand -f -a serve -d 'Start the persistent search server'
complete -c tgrep -n __fish_use_subcommand -f -a search -d 'Search for a pattern'
complete -c tgrep -n __fish_use_subcommand -f -a status -d 'Show index and server status'
complete -c tgrep -n __fish_use_subcommand -f -a count-files -d 'Count text files in a directory'
complete -c tgrep -n __fish_use_subcommand -f -a help -d 'Print help for a subcommand'

# Subcommand-specific options: index
complete -c tgrep -n '__fish_seen_subcommand_from index' -l force -d 'Force a full rebuild'
complete -c tgrep -n '__fish_seen_subcommand_from index; or __fish_seen_subcommand_from serve' -l exclude -r -d 'Exclude directories from indexing'
complete -c tgrep -n '__fish_seen_subcommand_from index' -l index-strategy -r -f -a 'memory external' -d 'How postings are accumulated'
complete -c tgrep -n '__fish_seen_subcommand_from index' -l index-buffer -r -d 'Arena size in MB before spilling to disk'

# Subcommand-specific options: serve
complete -c tgrep -n '__fish_seen_subcommand_from serve' -l no-watch -d 'Disable the file system watcher'
complete -c tgrep -n '__fish_seen_subcommand_from serve' -l max-memory -r -d 'Maximum memory budget in MB for initial scan'
complete -c tgrep -n '__fish_seen_subcommand_from serve' -l max-cpu -r -d 'Maximum CPU budget as percent of cores (1-100)'
complete -c tgrep -n '__fish_seen_subcommand_from serve' -l auto-save-mutations -r -d 'Mutations triggering a background save'
complete -c tgrep -n '__fish_seen_subcommand_from serve' -l watcher-queue-cap -r -d 'Max filesystem events buffered'

# --- Shared search/display options (top-level and all subcommands) ---
# Matching behavior
complete -c tgrep -s i -l ignore-case -d 'Case-insensitive matching'
complete -c tgrep -s s -l case-sensitive -d 'Force case-sensitive matching'
complete -c tgrep -s S -l smart-case -d 'Smart case: insensitive if pattern is lowercase'
complete -c tgrep -s F -l fixed-strings -d 'Treat pattern as a literal string'
complete -c tgrep -s w -l word-regexp -d 'Match whole words only'
complete -c tgrep -s v -l invert-match -d 'Show lines that do NOT match'
complete -c tgrep -s e -l regexp -r -d 'Additional pattern (repeatable)'
complete -c tgrep -s f -l file -r -F -d 'Read patterns from a file'
complete -c tgrep -s U -l multiline -d 'Enable multiline matching'
complete -c tgrep -l multiline-dotall -d 'Allow . to match newline (implies multiline)'
complete -c tgrep -s x -l line-regexp -d 'Only match when whole line matches'
complete -c tgrep -s P -l pcre2 -d 'Use PCRE-style engine (lookaround/backrefs)'
complete -c tgrep -l engine -r -f -a 'default pcre2 auto' -d 'Regex engine to use'
complete -c tgrep -l pcre2-version -d 'Print PCRE-style engine version and exit'
complete -c tgrep -l no-unicode -d 'Disable Unicode-aware matching'
complete -c tgrep -l regex-size-limit -r -d 'Upper size limit for compiled regex'
complete -c tgrep -l dfa-size-limit -r -d 'Upper size limit for regex DFA cache'

# Output modes
complete -c tgrep -s l -l files-with-matches -d 'Print only filenames with matches'
complete -c tgrep -l files-without-match -d 'Print files that do NOT match'
complete -c tgrep -s c -l count -d 'Print match count per file'
complete -c tgrep -s o -l only-matching -d 'Print only the matched parts of a line'
complete -c tgrep -s m -l max-count -r -d 'Limit matches per file'
complete -c tgrep -l files -d 'List files that would be searched'
complete -c tgrep -s q -l quiet -d 'Suppress output; exit code only'
complete -c tgrep -l json -d 'JSON output (one object per line)'
complete -c tgrep -l vimgrep -d 'Output in vim-compatible format'
complete -c tgrep -s r -l replace -r -d 'Replace each match with TEXT'
complete -c tgrep -l passthru -d 'Print both matching and non-matching lines'
complete -c tgrep -l stop-on-nonmatch -d 'Stop searching file after non-matching line'
complete -c tgrep -l stats -d 'Print query plan and timing stats'
complete -c tgrep -l debug -d 'Print debug messages (implies --stats)'
complete -c tgrep -l trace -d 'Print verbose trace messages (implies --stats)'

# Output formatting
complete -c tgrep -s A -l after-context -r -d 'Lines of context after each match'
complete -c tgrep -s B -l before-context -r -d 'Lines of context before each match'
complete -c tgrep -s C -l context -r -d 'Lines of context before and after'
complete -c tgrep -s H -l with-filename -d 'Print file name for each match'
complete -c tgrep -s I -l no-filename -d 'Suppress filenames in output'
complete -c tgrep -s n -l line-number -d 'Show line numbers'
complete -c tgrep -s N -l no-line-number -d 'Suppress line numbers'
complete -c tgrep -l heading -d 'Group matches by file with heading'
complete -c tgrep -l no-heading -d 'Do not group matches; flat output'
complete -c tgrep -l color -r -f -a 'auto always never' -d 'Color mode'
complete -c tgrep -s 0 -l null -d 'Use NUL byte as filename separator'
complete -c tgrep -l trim -d 'Trim leading/trailing whitespace'
complete -c tgrep -l column -d 'Show column number of first match'
complete -c tgrep -l no-column -d 'Do not show column numbers'
complete -c tgrep -s b -l byte-offset -d 'Print 0-based byte offset of each line'
complete -c tgrep -s M -l max-columns -r -d 'Do not print lines longer than NUM bytes'
complete -c tgrep -l max-columns-preview -d 'Print truncated preview of long lines'
complete -c tgrep -l count-matches -d 'Count individual matches, not lines'
complete -c tgrep -l include-zero -d 'Print zero count for files with no match'
complete -c tgrep -s p -l pretty -d 'Alias for --color always --heading --line-number'
complete -c tgrep -l context-separator -r -d 'String printed between context blocks'
complete -c tgrep -l no-context-separator -d 'Never print a context separator'
complete -c tgrep -l field-match-separator -r -d 'Separator for path/line/col of matches'
complete -c tgrep -l field-context-separator -r -d 'Separator for path/line/col of context'
complete -c tgrep -l path-separator -r -d 'Character to use as path separator'
complete -c tgrep -l sort -r -f -a 'none path modified accessed created' -d 'Sort results'
complete -c tgrep -l sortr -r -f -a 'none path modified accessed created' -d 'Sort results descending'
complete -c tgrep -l sort-files -d 'Deprecated alias for --sort path'

# File filtering
complete -c tgrep -s g -l glob -r -d 'Filter files by glob (repeatable)'
complete -c tgrep -l iglob -r -d 'Like --glob, but case-insensitive'
complete -c tgrep -l glob-case-insensitive -d 'Treat all --glob as case-insensitive'
complete -c tgrep -s t -l type -r -f -a '(tgrep --type-list 2>/dev/null | string split -f1 : | string trim)' -d 'Filter files by type (repeatable)'
complete -c tgrep -s T -l type-not -r -f -a '(tgrep --type-list 2>/dev/null | string split -f1 : | string trim)' -d 'Exclude files matching a type'
complete -c tgrep -l type-add -r -d 'Add or extend a type: name:glob'
complete -c tgrep -l type-clear -r -f -a '(tgrep --type-list 2>/dev/null | string split -f1 : | string trim)' -d 'Remove all globs for a type'
complete -c tgrep -l type-list -d 'Print all supported file types'
complete -c tgrep -l max-filesize -r -d 'Ignore files larger than NUM (K/M/G)'
complete -c tgrep -l no-max-filesize -d 'Apply no file size limit'
complete -c tgrep -s E -l encoding -r -f -a 'auto none utf-8 utf-8-sig utf-16le utf-16be' -d 'Text encoding to use'
complete -c tgrep -l no-encoding -d 'Reset --encoding back to auto'
complete -c tgrep -s a -l text -d 'Search binary files as if text'
complete -c tgrep -l binary -d 'Search binary files, report note'
complete -c tgrep -l max-depth -r -d 'Descend at most NUM directories'
complete -c tgrep -l one-file-system -d 'Do not cross file system boundaries'
complete -c tgrep -l ignore-file -r -F -d 'Read extra ignore globs from PATH'
complete -c tgrep -l ignore-file-case-insensitive -d 'Match --ignore-file globs insensitively'
complete -c tgrep -l no-ignore-dot -d 'Do not respect .ignore files'
complete -c tgrep -l no-ignore-exclude -d 'Do not respect .git/info/exclude'
complete -c tgrep -l no-ignore-files -d 'Do not respect --ignore-file arguments'
complete -c tgrep -l no-ignore-global -d 'Do not respect the global gitignore'
complete -c tgrep -l no-ignore-messages -d 'Suppress unparseable ignore file messages'
complete -c tgrep -l no-ignore-parent -d 'Do not respect parent ignore files'
complete -c tgrep -l no-ignore-vcs -d 'Do not respect .gitignore files'
complete -c tgrep -l no-require-git -d 'Respect .gitignore even outside git repo'

# Traversal / index / performance
complete -c tgrep -s . -l hidden -d 'Include hidden files and directories'
complete -c tgrep -l no-ignore -d 'Do not respect .gitignore files'
complete -c tgrep -s L -l follow -d 'Follow symbolic links'
complete -c tgrep -l no-messages -d 'Suppress unreadable file errors'
complete -c tgrep -s u -l unrestricted -d 'Unrestricted: -u no-ignore, -uu +hidden, -uuu +binary'
complete -c tgrep -l no-index -d 'Skip index, grep all files directly'
complete -c tgrep -l index-path -r -F -d 'Custom index directory'
complete -c tgrep -s j -l threads -r -d 'Number of threads to use'
complete -c tgrep -l mmap -d 'Compat only; always reads files directly'
complete -c tgrep -l no-mmap -d 'Compat only; always reads files directly'
complete -c tgrep -l line-buffered -d 'Flush output on every line'
complete -c tgrep -l block-buffered -d 'Buffer output in blocks'
complete -c tgrep -l no-config -d 'Compat only; reads no config file'
complete -c tgrep -l colors -r -d 'Compat only; colors not configurable'
complete -c tgrep -l crlf -d 'Compat only; always strips trailing CR'
complete -c tgrep -l no-crlf -d 'Compat only; always strips trailing CR'
complete -c tgrep -s z -l search-zip -d 'Not supported: does not decompress archives'

# Help / version
complete -c tgrep -s h -l help -d 'Print help'
complete -c tgrep -s V -l version -d 'Print version'
