[uni-macos]
src.github = "fiahfy/uni"
src.prefix = "v"
fetch.url = "https://github.com/fiahfy/uni/releases/download/v$ver/Uni-$ver.dmg"

[fish-na]
src.github = "ryoppippi/fish-na"
fetch.github = "ryoppippi/fish-na"

[debian-stable-slim-amd64]
src.manual = "stable-slim"
fetch.docker = "library/debian"
docker.arch = "amd64"

[debian-stable-slim-arm64]
src.manual = "stable-slim"
fetch.docker = "library/debian"
docker.arch = "arm64"
