[[plugins]]
repo = "eandrju/cellular-automaton.nvim"
on_cmd = "CellularAutomaton"

[[plugins]]
repo = "gw31415/nvim-tetris"
on_cmd = "Tetris"

[[plugins]]
repo = "seandewar/nvimesweeper"
on_cmd = "Nvimesweeper"

[[plugins]]
repo = "m4xshen/hardtime.nvim"
depends = ["nui.nvim", "plenary.nvim"]
on_cmd = "Hardtime"
lua_source = "require 'hardtime'.setup()"

# [[plugins]]
# repo = "gw31415/pets.nvim"
# depends = ["nui.nvim", "hologram.nvim"]
# on_event = "CmdlineEnter"
# if = 'environ()["TERM"] == "xterm-kitty"'
# lua_source = "require 'pets'.setup { row = 6 }"
