[[plugins]]
repo = "navarasu/onedark.nvim"

[[plugins]]
repo = "vim-denops/denops.vim"

[[plugins]]
repo = "lambdalisue/gin.vim"

[[plugins]]
repo = "lambdalisue/kensaku.vim"

[[plugins]]
repo = "yuki-yano/fuzzy-motion.vim"
depends = "kensaku.vim"
lua_add = '''
	vim.keymap.set("n", "<Space>", "<cmd>FuzzyMotion<cr>")
	vim.g.fuzzy_motion_labels = {
		'U', 'H', 'E', 'T', 'O', 'N', 'A', 'S', 'P', 'G', 'I', 'D', 'K', 'B', 'J', 'M',
	}
	vim.g.fuzzy_motion_matchers = { 'fzf', 'kensaku' }
'''

[[plugins]]
repo = "gw31415/skkeletal.vim"

[[plugins]]
repo = "vim-skk/skkeleton"
depends = "skkeletal.vim"
lua_add = '''
	vim.keymap.set({ "i", "c" }, "<C-j>", "<Plug>(skkeleton-enable)")
	vim.api.nvim_create_autocmd("User", { pattern = "skkeleton-mode-changed", command = "redraws" })
	_G.get_skkeleton_modestring = function()
		local mode = vim.fn["skkeleton#mode"]()
		if mode == "hira" then
			return "ひら"
		elseif mode == "kata" then
			return "カタ"
		elseif mode == "hankata" then
			return "半ｶﾀ"
		elseif mode == "zenkaku" then
			return "全英"
		elseif mode == "abbrev" then
			return "Abbr"
		else -- if mode == ''
			return "英数"
		end
	end
	vim.fn["skkeletal#config"]({
		eggLikeNewline = true,
		globalJisyo = "~/.skk/SKK-JISYO.L",
		markerHenkan = "▹",
		markerHenkanSelect = "▸",
		dvorak = true,
	})

	for _, map in pairs({
		{ "input",  "<c-e>", "" },
		{ "henkan", "<c-e>", "" },
		{ "input",  "<c-n>", "henkanFirst" },
		{ "henkan", "<c-n>", "henkanForward" },
		{ "henkan", "<c-p>", "henkanBackward" },
		{ "henkan", "<bs>",  "henkanBackward" },
		{ "henkan", "<c-h>", "" },
		{ "henkan", "<c-h>", "henkanBackward" },
	}) do
		vim.fn["skkeleton#register_keymap"](map[1], map[2], map[3])
	end
'''

[[plugins]]
repo = "lambdalisue/fern-hijack.vim"
