[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
lua_source = '''
	-- markdown treesitter のPluginの有効化
	vim.fn.setenv("EXTENSION_WIKI_LINK", 1)

	-- satysfiサーバのセットアップ
	local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
	parser_config.satysfi = {
		install_info = {
			url = "https://github.com/monaqa/tree-sitter-satysfi",
			files = { "src/parser.c", "src/scanner.c" }
		},
		filetype = "satysfi",
	}

	local parser_install_dir = vim.fn.stdpath("data") .. "/treesitter"
	vim.opt.runtimepath:append(vim.fn.stdpath("data") .. "/treesitter")
	require("nvim-treesitter.configs").setup({
		parser_install_dir = parser_install_dir,
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = { "org", "markdown" },
		},
		indent = {
			enable = true,
		},
		auto_install = true,
		ensure_installed = { 'org', 'satysfi', 'markdown' },
	})
	vim.wo.foldmethod = "expr"
	vim.wo.foldexpr = "nvim_treesitter#foldexpr()"
	vim.wo.foldenable = false
	vim.wo.foldlevel = 999
	vim.api.nvim_create_autocmd("BufEnter", {
		command = "TSEnable highlight",
	})
'''

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter-context"
depends = "nvim-treesitter"
on_event = "CursorHold"
lua_source = '''
	require 'treesitter-context'.setup {
		line_numbers = true,
		mode = 'topline',
		separator = '~'
	}
'''

[[plugins]]
repo = "https://gitlab.com/HiPhish/rainbow-delimiters.nvim"
depends = "nvim-treesitter"
on_event = "CursorHold"

[[plugins]]
repo = "Wansmer/treesj"
depends = "nvim-treesitter"
on_cmd = "TSJToggle"
lua_add = "vim.keymap.set('n', 'J', '<cmd>TSJToggle<cr>')"
lua_source = '''
	require 'treesj'.setup {
		use_default_keymaps = false, max_join_length = 150	
	}
'''

[[plugins]]
repo = "navarasu/onedark.nvim"
on_event = "BufEnter"
lua_source = '''
	require 'onedark'.setup {
		style = "darker",
		code_style = vim.g.goneovim ~= 1 and {
			comments = "none",
			functions = "bold",
			keywords = "none",
		} or nil,
	}
	require 'onedark'.load()
'''

[[plugins]]
repo = "thinca/vim-partedit"
[[plugins]]
repo = "monaqa/nvim-treesitter-clipping"
on_map = "<Plug>(ts-clipping-clip)"
lua_add = "vim.keymap.set('n', 'cx', '<Plug>(ts-clipping-clip)')"
depends = [ "nvim-treesitter", "vim-partedit" ]
