# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  debian-stable-slim = {
    pname = "debian-stable-slim";
    version = "stable-slim";
    src = dockerTools.pullImage {
      imageName = "library/debian";
      imageDigest = "sha256:8f0c555de6a2f9c2bda1b170b67479d11f7f5e3b66bb4a7a1d8843361c9dd3ff";
      sha256 = "sha256-/J3ZJIJuj0nTphvCNVTwfer9pIQx7d45Dx7ZdzCuwvw=";
      finalImageTag = "stable-slim";
    };
  };
  fish-na = {
    pname = "fish-na";
    version = "v0.1.2";
    src = fetchFromGitHub {
      owner = "ryoppippi";
      repo = "fish-na";
      rev = "v0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-Q/uqz5P3nKSWcX+4tKA3b1u+AiNDmW0bJ5rMYlvTt+Y=";
    };
  };
  uni-macos = {
    pname = "uni-macos";
    version = "0.1.1";
    src = fetchurl {
      url = "https://github.com/fiahfy/uni/releases/download/v0.1.1/Uni-0.1.1.dmg";
      sha256 = "sha256-txskKmSMAIhBVH/3DJQnojDW/Fg3xW6U/ilxcU1BKuU=";
    };
  };
}
