# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  fish-na = {
    pname = "fish-na";
    version = "v0.1.2";
    src = fetchFromGitHub {
      owner = "ryoppippi";
      repo = "fish-na";
      rev = "v0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-Q/uqz5P3nKSWcX+4tKA3b1u+AiNDmW0bJ5rMYlvTt+Y=";
    };
  };
  sponge = {
    pname = "sponge";
    version = "1.1.0";
    src = fetchFromGitHub {
      owner = "meaningful-ooo";
      repo = "sponge";
      rev = "1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-MdcZUDRtNJdiyo2l9o5ma7nAX84xEJbGFhAVhK+Zm1w=";
    };
  };
  uni-macos = {
    pname = "uni-macos";
    version = "0.1.1";
    src = fetchurl {
      url = "https://github.com/fiahfy/uni/releases/download/v0.1.1/Uni-0.1.1.dmg";
      sha256 = "sha256-txskKmSMAIhBVH/3DJQnojDW/Fg3xW6U/ilxcU1BKuU=";
    };
  };
}
