[[plugins]]
repo = "mfussenegger/nvim-dap"
on_lua = "dap"
lua_source = '''
vim.fn.sign_define('DapBreakpoint', { text = '', texthl = 'Macro', linehl = '', numhl = '' })
vim.fn.sign_define('DapBreakpointCondition', { text = '󰆗', texthl = 'Macro', linehl = '', numhl = '' })
vim.fn.sign_define('DapLogPoint', { text = '󰵛', texthl = '', linehl = 'Macro', numhl = '' })
vim.fn.sign_define('DapBreakpointRejected', { text = '', texthl = 'Macro', linehl = '', numhl = '' })

require 'dapui'.setup()

require 'dap'.listeners.before['event_initialized']['custom'] = function()
	require 'dapui'.open {}
end
require 'dap'.listeners.before['event_terminated']['custom'] = function()
	require 'dapui'.close {}
end
'''

[[plugins]]
repo = "nvim-neotest/nvim-nio"

[[plugins]]
repo = "rcarriga/nvim-dap-ui"
depends = "nvim-nio"
on_lua = "dapui"

[[plugins]]
repo = "theHamsta/nvim-dap-virtual-text"
on_source = "nvim-dap-ui"
lua_source = '''
require 'nvim-dap-virtual-text'.setup {
	enabled_commands = false,
}
'''
