onboarding = true

[terminal]
default_shell = "fish"

[ui]
show_agent_labels_on_pane_borders = true
switch_ascii_input_source_in_prefix = true
agent_panel_sort = "spaces"
ui.sound.enable = true

[ui.toast]
delivery = "system"

[update]
channel = "preview"

[keys]
prefix = "super+b"

[experimental]
kitty_graphics = true
