[tools]
usage = "latest"
flutter = "latest"
"cargo:math2img" = "latest"
deno = "latest"
python = "latest"
go = "latest"
"go:github.com/rhysd/vim-startuptime" = "latest"
act = "latest"
bun = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"cargo:sea-orm-cli" = "latest"
pnpm = "latest"

[settings]
experimental = true
