[tools]
"cargo:math2img" = "latest"
"cargo:openapi-tui" = "latest"
"cargo:sea-orm-cli" = "latest"
"go:github.com/rhysd/vim-startuptime" = "latest"
"go:golang.org/x/tools/cmd/godoc" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:aicommits" = "latest"
"npm:carbon-now-cli" = "latest"
"npm:esbuild" = "latest"
"npm:iconsur" = "latest"
act = "latest"
bun = "latest"
deno = "latest"
flutter = "latest"
go = "latest"
hugo = "latest"
jq = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
typst = "latest"
usage = "latest"

[settings]
experimental = true
