"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[directory]
truncate_to_repo = true
truncation_symbol = "…/"

[time]
disabled = true

[character]
error_symbol = "[\\(](yellow)[´o_o](bold red)[\\)](yellow)[ =3](cyan)"
success_symbol = "[\\(](yellow)[´‐_‐](bold green)[\\)](yellow)[ =3](cyan)"
