[[plugins]]
repo = "xzbdmw/colorful-menu.nvim"
on_lua = "colorful-menu"
lua_source = '''
require 'colorful-menu'.setup {}
'''

[[plugins]]
repo = "zbirenbaum/copilot.lua"
on_cmd = "Copilot"
lua_source = '''
require 'copilot'.setup {
	suggestion = { enabled = false },
	panel = { enabled = false },
	copilot_node_command = 'node'
}
'''

[[plugins]]
repo = "Kaiser-Yang/blink-cmp-git"
[[plugins]]
repo = "fang2hou/blink-copilot"
depends = "copilot.lua"
lua_source = '''
require 'blink-copilot'.setup {
	max_completions = 3,
	max_attempts = 5,
}
'''
[[plugins]]
repo = "saghen/blink.cmp"
depends = ["blink-copilot", "blink-cmp-git"]
on_event = ["InsertEnter", "CmdlineEnter", "LspAttach"]
extAttrs.installerBuild = "nix run .#build-plugin"
lua_source = '''
require 'blink.cmp'.setup {
	sources = {
		default = { 'snippets', 'lsp', 'copilot', 'path', 'buffer' },
		per_filetype = {
			lua = { inherit_defaults = true, 'lazydev' },
			gitcommit = { inherit_defaults = true, 'git' },
		},
		providers = {
			copilot = {
				name = 'copilot',
				module = 'blink-copilot',
				score_offset = -100,
				async = true,
			},
			lazydev = {
				name = 'LazyDev',
				module = 'lazydev.integrations.blink',
				score_offset = 100,
			},
			git = {
				module = 'blink-cmp-git',
				name = 'Git',
			},
		},
	},
	keymap = { preset = 'super-tab' },
	completion = {
		documentation = { auto_show = true, auto_show_delay_ms = 100 },
		menu = {
			draw = {
				components = {
					label = {
						text = function(ctx)
							return require 'colorful-menu'.blink_components_text(ctx)
						end,
						highlight = function(ctx)
							return require 'colorful-menu'.blink_components_highlight(ctx)
						end,
					},
				},
			}
		}
	},
	cmdline = {
		keymap = {
			preset = 'inherit',
			['<space>'] = {
				function(cmp)
					local function fallback()
						vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<space>', true, false, true), 'n', true)
					end

					if vim.tbl_contains({ ':', '@' }, vim.fn.getcmdtype()) and cmp.is_visible() then
						return cmp.accept { callback = fallback }
					end
					return fallback()
				end,
			},
		},
		completion = {
			menu = { auto_show = true },
		},
	},
	signature = { enabled = true },
}

if not vim.fn.has 'nvim-0.11' then
	vim.lsp.config('*', {
		capabilities = require 'blink.cmp'.get_lsp_capabilities()
	})
end
'''
