complete -c dot -n '__fish_use_subcommand' -a sh -d 'Open the dotfiles development shell'
complete -c dot -n '__fish_use_subcommand' -a gc -d 'Collect Nix garbage'
complete -c dot -s h -l home -d 'Apply user dotfiles'
complete -c dot -s d -l darwin -d 'Apply nix-darwin on macOS'
complete -c dot -s a -l all -d 'Apply user dotfiles and nix-darwin on macOS'
complete -c dot -s u -l update -d 'Update flake.lock only'
