[[plugins]]
repo = "ravitemer/mcphub.nvim"

[[plugins]]
repo = "folke/sidekick.nvim"
on_event = "VeryLazy"
on_cmd = "Sidekick"
lua_after = '''
require 'sidekick'.setup {
	signs = {
		enabled = true,
		icon = "",
	},
	cli = {
		mux = {
			backend = 'tmux',
			enabled = true,
		},
	},
	nes = { enabled = false },
}
vim.api.nvim_create_user_command('Sidekick', function(args)
	local model = args.fargs[1]
	require 'sidekick.cli'.toggle { focus = true, name = model }
end, {
	nargs = '?',
	complete = function()
		---@param a sidekick.cli.Tool
		---@return string[]
		return vim.tbl_map(function(a)
			return a.name
		end, require 'sidekick.cli'.get_tools {
			installed = true,
		});
	end,
})
vim.keymap.set('n', '<Tab>', function()
		if not require 'sidekick'.nes_jump_or_apply() then
			return '<Tab>'
		end
	end,
	{
		expr = true,
		desc = 'Goto/Apply Next Edit Suggestion',
	}
)
'''
