[[devices]]
device = "MacBook Airのマイク"
name = "mic"

[[devices]]
device = "BlackHole 2ch"
limiter = true

[[routes]]
from = "VT-4"
from_channels = [
    3,
    4,
]
to = "BlackHole 2ch"
to_channels = [
    1,
    2,
]
