[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python", "node"]

[tools]
aube = "latest"
"gem:terminal-notifier" = { version = "latest", os = "macos" }
# "github:bit-vcs/bit" = { version = "latest", os = ["macos", "linux-x64"] }
"github:gw31415/commitgen" = { version = "latest", bin = "commitgen" }
"github:gw31415/rsplug.nvim" = { version = "latest", bin = "rsplug" }
"github:gw31415/audiorouter" = "latest"
go = "1.26.4"
# "go:github.com/kahing/goofys" = "0.20.0"
node = { version = "latest", os = "macos" }
"npm:fish-lsp" = "latest"
# "npm:takt" = "latest"
"npm:trash-cli" = "latest"
"pipx:git+https://github.com/gw31415/aiocr.git" = "latest"
pnpm = "latest"
usage = "latest"
"npm:gnhf" = "latest"
"github:isak102/neowright" = "latest"
"aqua:tak848/ccgate" = "latest"
"cargo:ghzinga" = "latest"
