[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python", "node"]

[tools]
aube = "latest"
"gem:terminal-notifier" = { version = "latest", os = "macos" }
"github:gw31415/commitgen" = { version = "latest", bin = "commitgen" }
"github:gw31415/rsplug.nvim" = { version = "latest", bin = "rsplug" }
"github:gw31415/audiorouter" = "latest"
node = "latest"
"npm:fish-lsp" = "latest"
"npm:trash-cli" = "latest"
"pipx:git+https://github.com/gw31415/aiocr.git" = "latest"
pnpm = "latest"
usage = "latest"
"github:isak102/neowright" = "latest"
# "cargo:https://github.com/jkcoxson/idevice_pair" = "latest"
"npm:hunkdiff" = "latest"
stylua = "latest"
"cargo:mdbook" = "latest"
"github:can1357/oh-my-pi" = "latest"
"cargo:https://github.com/nakasyou/local-mcp" = "latest"
"github:openai/tunnel-client" = "latest"
"pipx:serena-agent" = "latest"
tssh = "latest"
