[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python", "node"]

[tools]
aube = "latest"
"gem:terminal-notifier" = { version = "latest", os = "macos" }
"github:bit-vcs/bit" = { version = "latest", os = ["macos", "linux-x64"] }
go = "1.25.5"
# "go:github.com/kahing/goofys" = "0.20.0"
node = { version = "latest", os = "macos" }
"npm:fish-lsp" = "latest"
"npm:takt" = "latest"
"npm:trash-cli" = "latest"
pnpm = "latest"
usage = "2"
