# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Setup vim-startuptime
      run: go install github.com/rhysd/vim-startuptime@latest
        
    - name: Setup Chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${GITHUB_REPOSITORY%/*}
