# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup vim-startuptime
        run: go install github.com/rhysd/vim-startuptime@latest

      - name: Setup Chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${GITHUB_REPOSITORY%/*}

      - name: Setup Neovim
        run: |
          sudo add-apt-repository -y ppa:neovim-ppa/unstable
          sudo apt update -y
          sudo apt install -y neovim

      - name: Measure vim-startuptime & Create tweet
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "TWEET<<$EOF" >> "$GITHUB_ENV"
          RESULT=$(vim-startuptime -vimpath nvim)
          echo "${RESULT}" | head -n 6 | awk '{print ">  " $0}' >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"

      - name: Post tweet
        uses: InfraWay/tweet-action@v1.0.1
        with:
          status: ${{ env.TWEET }}
          api_key: ${{ secrets.TWITTER_API_KEY }}
          api_key_secret: ${{ secrets.TWITTER_API_KEY_SECRET }}
          access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
